<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_badssl.com-client.p12</name>
   <tag></tag>
   <elementGuidId>02ae2cd3-362c-4544-be17-cf8caec4e43b</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td > a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/certs/badssl.com-client.p12' and (text() = 'badssl.com-client.p12' or . = 'badssl.com-client.p12')]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;table-wrapper&quot;]/table/tbody/tr[1]/td[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>619d159c-32c5-4e26-b149-427e85e9e6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/certs/badssl.com-client.p12</value>
      <webElementGuid>3beb635e-cce2-4fa0-b34f-c9f525042800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>badssl.com-client.p12</value>
      <webElementGuid>d1a50a11-4ffe-41c0-952b-54e9b5d880b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-wrapper&quot;)/table[1]/tbody[1]/tr[1]/td[1]/a[1]</value>
      <webElementGuid>6b1cb0a9-8681-4b7c-ad63-b72881a09d9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table-wrapper']/table/tbody/tr/td/a</value>
      <webElementGuid>36e8575c-56ae-48e8-b74d-07ce5e5071ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'badssl.com-client.p12')]</value>
      <webElementGuid>30eee6de-6e06-4ceb-8eb8-1344a787da1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Format'])[1]/following::a[1]</value>
      <webElementGuid>008f426e-d8c9-4c73-a3af-dcb6536a30a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::a[1]</value>
      <webElementGuid>fed423d5-4f3a-4625-ba02-14eab1b63cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='badssl.com'])[2]/preceding::a[1]</value>
      <webElementGuid>f9798658-84ab-4ac2-a64e-f8c729b27d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PKCS #12'])[1]/preceding::a[1]</value>
      <webElementGuid>7f57d996-bf12-4575-9134-8c9006663f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='badssl.com-client.p12']/parent::*</value>
      <webElementGuid>ccee494f-368f-480d-b103-5193b45be950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/certs/badssl.com-client.p12')]</value>
      <webElementGuid>9da8847d-1cd4-48d6-8803-eb126ace9c2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>af64b878-6c07-44cf-a815-872ceb9e5c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/certs/badssl.com-client.p12' and (text() = 'badssl.com-client.p12' or . = 'badssl.com-client.p12')]</value>
      <webElementGuid>ef6944f3-f957-42e8-b068-124d429b1fa8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
