<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Certificate Downloads</name>
   <tag></tag>
   <elementGuidId>f36eded8-aa08-44b5-9c8b-2dcdd9ca05de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='links']/div/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8a253837-aa0f-40fe-818e-98947c4f4931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/download/</value>
      <webElementGuid>46938d8f-bbb4-4b5c-aff6-afa0f5b2b032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>e58ab41c-eadd-4131-bbd5-ad702cfdf8a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bullet-list</value>
      <webElementGuid>5ad26ec5-b883-4808-aa0a-c09d94b0d9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Certificate Downloads</value>
      <webElementGuid>21ad0053-3e7f-4fdd-bb07-4766f9920272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;links&quot;)/div[@class=&quot;column&quot;]/div[@class=&quot;group&quot;]/a[@class=&quot;bullet-list&quot;]</value>
      <webElementGuid>2eec05d9-158b-41ae-a589-f94b8e9696d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='links']/div/div[3]/a</value>
      <webElementGuid>0c4797d5-7d7f-43f4-ab11-c301cb8b30bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Certificate Downloads')]</value>
      <webElementGuid>59ac8e1a-a592-401e-be5a-b3087e370fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='🎟'])[1]/following::a[1]</value>
      <webElementGuid>750d5d08-99e2-4d03-9851-da74e123e28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='client'])[1]/preceding::a[1]</value>
      <webElementGuid>9c3eadb1-060a-488b-a44f-68c1d24af5a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='client-cert-missing'])[1]/preceding::a[2]</value>
      <webElementGuid>ed550b5a-9d80-46ba-886b-8f899c84e262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Certificate Downloads']/parent::*</value>
      <webElementGuid>a1942ef7-df0d-4f3a-8c26-fdb00cb880e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/download/')]</value>
      <webElementGuid>76242f3c-81f0-4282-85ff-56a3581cb925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>bc3770b9-6016-45b2-9a46-ecec074081ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/download/' and (text() = 'Certificate Downloads' or . = 'Certificate Downloads')]</value>
      <webElementGuid>9aea19d2-e2d7-4e7d-94c6-a4a1eb69d14f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
