<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_client</name>
   <tag></tag>
   <elementGuidId>782ea939-a934-4849-a5f7-81cb43d9fd6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='links']/div/div[3]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>65447941-18e2-49e6-93cf-a0ad22018340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://client.badssl.com/</value>
      <webElementGuid>d417af91-1501-40c0-98b5-969f7e5fb98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>good</value>
      <webElementGuid>583e3c4c-f32a-44d9-809b-f537cf064ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>client</value>
      <webElementGuid>6745e1b9-fd61-4f97-80c8-249c25a63d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;links&quot;)/div[@class=&quot;column&quot;]/div[@class=&quot;group&quot;]/a[@class=&quot;good&quot;]</value>
      <webElementGuid>763ed2d5-66ef-4eed-b3f9-455b9e234c11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='links']/div/div[3]/a[2]</value>
      <webElementGuid>6383c416-a97f-4bf8-adbe-1f09840df4b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'client')]</value>
      <webElementGuid>f8aa3b2d-a946-4651-bcd7-2a8150658e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Certificate Downloads'])[1]/following::a[1]</value>
      <webElementGuid>39baee8f-2311-4b22-9552-534c4cfaef5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='🎟'])[1]/following::a[2]</value>
      <webElementGuid>1664b20e-94aa-4bdb-a885-e85fa8884fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='client-cert-missing'])[1]/preceding::a[1]</value>
      <webElementGuid>6ef89304-35a0-48e0-bb46-892819b60107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='client']/parent::*</value>
      <webElementGuid>a20e3ddb-0e66-404b-a479-d77aa91dfc84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://client.badssl.com/')]</value>
      <webElementGuid>64c664c9-1e9f-4ee4-b14b-507f713a4f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a[2]</value>
      <webElementGuid>821e7633-0d70-4b3f-97b3-e4869e4b10dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://client.badssl.com/' and (text() = 'client' or . = 'client')]</value>
      <webElementGuid>5ae0cf55-5348-4593-8d37-4db595a3a3fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
